[versions]
# Plugins
shadow = "9.0.0-beta4"
run-paper = "2.3.1"
spotless = "7.0.0.BETA4"
paper-userdev = "2.0.0-beta.18"

# Tooling
kotlin-coroutines = "1.10.1"
guava = "33.4.0-jre"
slf4j = "2.0.16"
caffeine = "3.1.8"
cloud = "2.0.0"
cloud-minecraft = "2.0.0-beta.10"

# Misc
adventure-core = "4.18.0"

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
paper-userdev = { id = "io.papermc.paperweight.userdev", version.ref = "paper-userdev" }

[libraries]
# Tooling
kotlin-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
caffeine = { group = "com.github.ben-manes.caffeine", name = "caffeine", version.ref = "caffeine" }
cloud-paper = { group = "org.incendo", name = "cloud-paper", version.ref = "cloud-minecraft" }
cloud-kotlin-extensions = { group = "org.incendo", name = "cloud-kotlin-extensions", version.ref = "cloud" }
cloud-kotlin-coroutines = { group = "org.incendo", name = "cloud-kotlin-coroutines", version.ref = "cloud" }

# Misc
adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "adventure-core" }
